---
# tasks file for 01-update
  - include_vars: "{{ playbook_dir }}/vars.yml" 

  - name: Update 
    apt:
      name: '*'
      state: 'latest'
      update_cache: yes
    register: apt_res
    retries: 300
    delay: 10
    until: apt_res is success   

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file  
  
  - name: Reboot
    reboot:
      msg: Reboot
      reboot_timeout: 3600
    when: reboot_required_file.stat.exists == true


  - name: Create directory
    file:
      path: /usr/local/share/ca-certificates/extra/
      state: directory

  - name: Transfer the ca certificate
    copy:
      src: "{{ playbook_dir }}/certs/regca.crt" 
      dest: /usr/local/share/ca-certificates/extra/regca.crt      

  - name: Transfer the ca certificate from openstack
    copy:
      src: "{{ openstack.cacert }}" 
      dest: /usr/local/share/ca-certificates/extra/openstack.crt                
  
  - name: Update ca trusted list
    shell: |
      /usr/sbin/update-ca-certificates
    args:
      executable: /bin/bash

  - name: Install required packages for nfs
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - nfs-kernel-server 
        - rsync      
