---
# tasks file for 01-update
  - include_vars: "{{ playbook_dir }}/vars.yml" 

  - name: Update /etc/hosts
    template:
      src: etc_hosts.j2
      dest: /etc/hosts

  - name: Update sysctl.conf
    lineinfile:
      path: /etc/sysctl.conf
      line: 'vm.max_map_count=262144'

  - name: Apply sysctl changes
    command: sysctl --system
    changed_when: false

  - name: Update 
    apt:
      name: '*'
      state: 'latest'
      update_cache: yes
    register: apt_res
    retries: 300
    delay: 10
    until: apt_res is success   

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file  
  
  - name: Notify reboot
    shell: echo "reboot"  > /tmp/reboot
    when: reboot_required_file.stat.exists == true    
    notify: reboot

  - name: Enable sctp module
    copy:
      src: modules
      dest: /etc/modules
    notify: reboot

  - name: Create directory
    file:
      path: /usr/local/share/ca-certificates/extra/
      state: directory

  - name: Transfer the ca certificate
    copy:
      src: "{{ playbook_dir }}/certs/regca.crt" 
      dest: /usr/local/share/ca-certificates/extra/regca.crt      

  - name: Transfer the ca certificate from openstack
    copy:
      src: "{{ openstack.cacert }}" 
      dest: /usr/local/share/ca-certificates/extra/openstack.crt    

  - name: Transfer ca certificates from trusted_ca_list
    copy:
      src: "{{ item.src_file_name }}"
      dest:  "/usr/local/share/ca-certificates/extra/{{ item.name }}"
    loop:
      "{{ trusted_ca_list }}"            
  
  - name: Update ca trusted list
    shell: |
      /usr/sbin/update-ca-certificates
    args:
      executable: /bin/bash

  - name: Install required packages for nfs
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - nfs-kernel-server 
        - rsync      

  