

- hosts: WORKER
  user: debian
  #gather_facts: no
  #serial: 1
  become: yes
  tasks:
    - name: Activate all interfaces
      shell: |
        for i in `ip link | grep  -oP '(?<=:\s)(eth.*)(?=:\s)'`; do ip link set ${i} up; done
        for i in `ip link | grep  -oP '(?<=:\s)(ens.*)(?=:\s)'`; do ip link set ${i} up; done