    
- hosts: localhost
  tasks:
    - include_vars: "{{ playbook_dir }}/vars.yml"
    - name: Wait for connection
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 3000
      loop:
        "{{ all_external }}"
     
- hosts: MASTER, WORKER, BASTIAN
  user: ubuntu
  become: true
  roles:
    - role: 02-etc-hosts 

- hosts: REGISTRY, NFS
  user: debian
  become: true
  roles:
    - role: 02-etc-hosts     



