- hosts: localhost
  roles:
    - role: 01-certs
    
- hosts: localhost
  tasks:
    - include_vars: "{{ playbook_dir }}/vars.yml"
    - name: Wait for connection
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 3000
      loop:
        "{{ all_external }}"

    - name: Clear files directory
      file:
        path: "{{ playbook_dir }}/files"
        state: absent

    - name: Create files directory
      file:
        path: "{{ playbook_dir }}/files"
        state: directory        

# Update
- hosts: NFS, REGISTRY
  user: debian
  become: true
  roles:
    - role: 02-update 

# Update
- hosts: MASTER, WORKER, BASTIAN
  user: ubuntu
  become: true
  roles:
    - role: 02-update     

- hosts: REGISTRY
  user: debian
  become: true
  roles:
    - role: 03-harbor

- hosts: NFS
  user: debian
  become: true
  roles:
    - role: 04-nfs     

- hosts: BASTIAN
  user: ubuntu  
  roles:
    - role: 05-k8s-inst  

- hosts: MASTER
  user: ubuntu
  run_once: yes
  become: yes
  tasks:
    - name: Get kubenconfig
      fetch:
        src: /root/.kube/config
        dest: "{{ playbook_dir }}/files/kubeconfig"
        flat: yes

- hosts: BASTIAN
  user: ubuntu
  tasks:
    - name: Clear kubeconfig
      file:
        path: /home/ubuntu/.kube/
        state: absent

    - name: Create kubeconfig directory
      file:
        path: /home/ubuntu/.kube/
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Send kubeconfig to bastian
      copy:
        src: "{{ playbook_dir }}/files/kubeconfig"        
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0700'

- hosts: BASTIAN
  user: ubuntu
  roles:
    - role: 06-ingress
    - role: 06-1-multus
    - role: 07-cloud-controller-manager
    - role: 08-nfs-storageclass    
    - role: 09-istio
      when: run_istio  == "yes"
      
