    
- hosts: localhost
  tasks:
    - include_vars: "{{ playbook_dir }}/vars.yml"
    - name: Wait for connection
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 3000
      loop:
        "{{ all_external }}"
     

- hosts: WORKER
  user: ubuntu
  become: true
  roles:
    - role: 02-update 

- hosts: BASTIAN
  user: ubuntu  
  roles:
    - role: 10-k8s-scale


