---
# tasks file for 06-ingress
# Reference: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  - include_vars: "{{ playbook_dir }}/vars.yml"  

  - name: Clear directories
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /home/ubuntu/multus-cni
      - /home/ubuntu/whereabouts
      
  - name: Clone multus-cni repository
    git:
      repo: https://github.com/k8snetworkplumbingwg/multus-cni.git
      dest: /home/ubuntu/multus-cni
      version: release-3.7
      
  - name: Apply multus installation
    shell: |
      cd /home/ubuntu/multus-cni
      cat ./images/multus-daemonset.yml | kubectl apply -f -  
  
  - name: Clone whereabouts repository
    git:
      repo: https://github.com/k8snetworkplumbingwg/whereabouts
      dest: /home/ubuntu/whereabouts
      version: v0.6.2
  
  - name: Apply whereabouts installation
    shell: |
      cd /home/ubuntu/whereabouts
      kubectl apply \
          -f doc/crds/daemonset-install.yaml \
          -f doc/crds/whereabouts.cni.cncf.io_ippools.yaml \
          -f doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml    

  - name: Cleanup
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /home/ubuntu/multus-cni
      - /home/ubuntu/whereabouts        


