---
# tasks file for 08-nfs-storageclass
  - include_vars: "{{ playbook_dir }}/vars.yml" 

  - name: Extract helm
    become: yes
    unarchive:
      src: https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
      dest: /usr/local/bin/
      remote_src: yes
      owner: root
      group: root
      mode: "0755"
      extra_opts: 
        - --strip-components=1
        - --wildcards
        - '*/helm'

  - name: Delete namespace if exists
    ignore_errors: yes
    shell: kubectl delete namespace nfs-provisioner

  - name: Create nfs namespace
    shell: |
       kubectl create namespace nfs-provisioner
    register: outp
    until: "outp is not failed"
    retries: 100
    delay: 10

  - name: Add nfs-subdir-external-provisioner repo
    shell: |       
        helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    register: outp
    until: "outp is not failed"
    retries: 100
    delay: 10  

  - name: Install nfs provisioner
    shell: |
       helm install -n nfs-provisioner nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
          --set nfs.server={{ nfs_fqdn }} --set nfs.path=/srv/nfs --set storageClass.name=nfs-provisioner --set storageClass.defaultClass=nfs-provisioner
    register: outp
    until: "outp is not failed"
    retries: 100
    delay: 10        